version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=app
      - DB_PASSWORD=app  # Changed from DB_PASS to DB_PASSWORD
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=app.settings  # Add this line
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app

volumes:
  dev-db-data: